# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'barbellcoach' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for barbellcoach
  pod 'Firebase/Core', '~> 4.13.0'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'

  target 'barbellcoachTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'barbellcoach-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for barbellcoach-tvOS

  target 'barbellcoach-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
